backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "staff"
    label: "University Staff"
    folder: "content/staff"
    create: true
    editor:
      visualEditing: true
    view_filters:
      - label: "Department of Mathematics"
        field: department
        pattern: 'math'
      - label: "Department of Physics"
        field: department
        pattern: 'phy'
      - label: "Department of Computer Science"
        field: department
        pattern: 'cs'
    view_filters:
      - label: "Lecturer"
        field: title
        pattern: 'Lecturer'
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { 
          label: "Title", 
          name: "title", 
          widget: "select",
          options: ["Head", "Professor", "Associate Professor", "Lecturer", "Tutor"]
        }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Phone", name: "phone", widget: "string", required: false }
      - {
          label: "Department",
          name: "department",
          widget: "select",
          options: ["cs", "phy", "math"]
        }
      - { label: "Bio", name: "body", widget: "markdown", required: false }
