backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.md"
        label: "Home"
        name: "home"
        fields: [ { label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" } ]
      - file: "about.md"
        label: "About"
        name: "about"
        fields: [ { label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" } ]
      - file: "contact.md"
        label: "Contact"
        name: "contact"
        fields: [ { label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" } ]
